my-portfolio-website/
Home.html
Style.css
Script.js
images/
https://drive.google.com/file/d/1gWyHNy-LEBOG91-BDw_cMQZbUELSBe4X/view?usp=share_link
https://drive.google.com/file/d/1nTACul6Wv0Vl0BlUeFYDi72R5Dsmijk4/view?usp=share_link
https://drive.google.com/file/d/1nTACul6Wv0Vl0BlUeFYDi72R5Dsmijk4/view?usp=share_link
https://drive.google.com/file/d/1nTACul6Wv0Vl0BlUeFYDi72R5Dsmijk4/view?usp=share_link
https://drive.google.com/file/d/1DX3_5Jmb1MrhnDNsJsfHDirOaN_sByDH/view?usp=share_link
https://drive.google.com/file/d/1DX3_5Jmb1MrhnDNsJsfHDirOaN_sByDH/view?usp=share_link
README.md
